# Generated by Django 3.2.7 on 2021-10-30 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.FileField(upload_to='Uploaded Files/')),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocContables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.FileField(upload_to='Uploaded Files/')),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
                ('Guia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocsEditables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.TextField(max_length=2000)),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosEje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.FileField(default=0, upload_to='Uploaded Files/')),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('puesto', models.CharField(max_length=50)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=50)),
                ('horaRegisto', models.DateField()),
                ('horaReunion', models.DateField()),
                ('link', models.CharField(max_length=150)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
                ('IDUsuarioAdmin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.usuarioadmin')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioInscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=20)),
                ('dMunicipio', models.CharField(max_length=250)),
                ('Direccion', models.CharField(max_length=250)),
                ('fotografiaPersonal', models.FileField(upload_to='Uploaded Files/')),
                ('cartaRecomendacion', models.FileField(upload_to='Uploaded Files/')),
                ('cartaLaboral', models.FileField(upload_to='Uploaded Files/')),
                ('tituloyDiplomas', models.FileField(upload_to='Uploaded Files/')),
                ('CUI', models.CharField(max_length=15)),
                ('fotografiaDPI', models.FileField(upload_to='Uploaded Files/')),
                ('fotografiaRTU', models.FileField(upload_to='Uploaded Files/')),
                ('antecedentespenales', models.FileField(upload_to='Uploaded Files/')),
                ('antecedentespoliciacos', models.FileField(upload_to='Uploaded Files/')),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now_add=True)),
                ('IDDepartamentos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.departamento')),
                ('IDusuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('profe', models.ManyToManyField(to='home.Profesion')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDReuniones', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.reuniones')),
                ('IDUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
    ]
