# Generated by Django 3.2.7 on 2021-10-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniones',
            name='horaRegisto',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reuniones',
            name='horaReunion',
            field=models.DateField(),
        ),
    ]
