# Generated by Django 3.2.6 on 2021-10-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contraseña_usuario_contraseñau'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadmin',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
    ]
