# Generated by Django 3.2.6 on 2021-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usuarioadmin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioadmin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
