# Generated by Django 3.2.7 on 2021-10-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_documentoseje_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoseje',
            name='Contenido',
            field=models.FileField(upload_to='Uploaded Files/'),
        ),
    ]
