# Generated by Django 3.2.7 on 2021-10-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211014_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario_Profesion',
        ),
    ]
