# Generated by Django 3.2.6 on 2021-10-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_docseditables_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docseditables',
            name='Contenido',
            field=models.TextField(max_length=2000),
        ),
    ]
