# Generated by Django 3.2.7 on 2021-10-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211014_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioinscripcion',
            old_name='dMunicipioDireccionDeRecibido',
            new_name='Direccion',
        ),
        migrations.AddField(
            model_name='formularioinscripcion',
            name='dMunicipio',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formularioinscripcion',
            name='profe',
            field=models.ManyToManyField(to='home.Profesion'),
        ),
    ]
