# Generated by Django 3.2.7 on 2021-10-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_formulario_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.FileField(upload_to='Uploaded Files/')),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DocContables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.FileField(upload_to='Uploaded Files/')),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
                ('Guia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocsEditables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.FileField(upload_to='Uploaded Files/')),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosEje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.FileField(upload_to='Uploaded Files/')),
                ('Tipo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
