# Generated by Django 3.2.7 on 2021-10-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_docseditables_contenido'),
        ('home', '0023_delete_formulario_reuniones'),
    ]

    operations = [
    ]
